package com.gnews.utils

const val DELAY_CLOSE_KEYBOARD = 100L
const val DELAY_OPEN_KEYBOARD = 300L
const val DELAY_OPEN_KEYBOARD_AFTER_ANIMATED_NAVIGATION = 800L
const val DELAY_CLOSE_BOTTOM_SHEET = 300L
const val DELAY_DEBOUNCE_CLICK = 300L
const val DELAY_BOTTOM_NAV_VIEW_SHOW = 500L
